set nocompatible

" Enable syntax highlighting and filetype support.
syntax enable
filetype plugin indent on

" Use true color when the terminal supports it.
if has('termguicolors')
  set termguicolors
endif

colorscheme default

" Neutral syntax colors: avoid blue-heavy defaults.
function! s:basic_no_blue_colors() abort
  highlight Normal ctermfg=252 ctermbg=NONE guifg=#d0d0d0 guibg=NONE
  highlight Comment ctermfg=244 guifg=#808080
  highlight Constant ctermfg=180 guifg=#d7af87
  highlight String ctermfg=114 guifg=#87d787
  highlight Identifier ctermfg=223 guifg=#ffd7af
  highlight Function ctermfg=223 guifg=#ffd7af
  highlight Statement ctermfg=179 guifg=#d7af5f
  highlight Keyword ctermfg=179 guifg=#d7af5f
  highlight Type ctermfg=150 guifg=#afd787
  highlight PreProc ctermfg=180 guifg=#d7af87
  highlight Special ctermfg=216 guifg=#ffaf87
endfunction

augroup basic_vim_colors
  autocmd!
  autocmd ColorScheme * call s:basic_no_blue_colors()
augroup END

call s:basic_no_blue_colors()
